### ISSUE TITLE
Major Request - Need a way to control spawns 1.10.2 - Forge 221 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [bigbang87/deadly-monsters#1]
I have been watching this mod quit a lot but as long as the spawns are not in my control both weight and frequency I can not use this. I am interested in more creatures but not at the cost of spawn overflow.

**Comment by bigbang87** [comment]
There is config file (configs/deadly_monsters) where you can configure spawning controls.

**Comment by P3rf3ctXZer0** [comment]
Then the config does contain spawn control in a usable fashion else I would not have made this post (unless I was really exhausted) Otherwise I am sure I will revisit your mod in the future.
