### ISSUE TITLE
Configs on per Dimension Spawn of Mobs

### ISSUE THREAD

**Issue by Vyraal1** [bigbang87/deadly-monsters#10]
Could there be an additional config on which dimensions the deadly monsters can spawn? I have Twilight Forest/BetweenLands installed in my upcoming pack and would like to control which of the deadly mobs fit in there.

In addition would it be possible to have some more transparency, either in the wiki or in the configs of the spawning conditions of some of the mobs? It might be RNG but I'm trying to figure out conditions on why some mobs spawn and other's dont, eg in a dark creative testing world I haven't seen any Bloody Maidens yet. I don't know Java very well, and I already tried looking through the source but I wasn't able to find the conditions of each mob, any help would be appreciated as I'm trying to apply some mob modifiers such as Scaling Health and Infernal Mobs and wanted to plan out progression.

**Comment by bigbang87** [comment]
What version of Minecraft you use?

**Comment by Vyraal1** [comment]
This is for 1.12.2, using latest version of Deadly Monsters, latest version of Forge (2559).

**Comment by bigbang87** [comment]
I did some research and i should be able to add an option for spawning in nether. Unfortunately config for spawning mobs in bioms from another mod is much more complicated.

**Comment by Vyraal1** [comment]
That's fine, thanks for looking into this! Would it also be possible to have spawning on a per-dimension basis rather than per biome then? Such as a whitelist based on dimension ID number, at the bottom of each config section for each mob, you can put in some integers and allow the mobs spawns for those dimensions.

**Comment by Sunconure11** [comment]
What became of this? I would like to tweak mobs per dimension in my pack as well.

**Comment by bigbang87** [comment]
Well i don't think that in the near future it will be possible to me, especially because I work alone on this mod. The only way to do this is finding some help from others on this feature.
