### ISSUE TITLE
Mutant Steve Can Break Bedrock

### ISSUE THREAD

**Issue by TeetoKaziim** [bigbang87/deadly-monsters#11]
I think this is because Bedrock (And other "unbreakable" blocks like it) uses a hardness level of -1, and it seems like block hardness is what steve is looking for to decide if he can break things?

**Comment by bigbang87** [comment]
You're right, code for breaking blocks:

`	if (hardness < hardnessTreshold) {
		randomChance = random.nextFloat();
		if (randomChance < destroyChance) {
			this.attacker.world.destroyBlock(blockToDestroyPos, true);
			destroyedBlock = true;
		}
	}`

so i need to fix it.
