### ISSUE TITLE
[1.12.2] Harpoon too inbalance

### ISSUE THREAD

**Issue by KorDum** [bigbang87/deadly-monsters#12]
It doesn't damaged and allows you to get fish endlessly.
In addition, the chance of catching is very high.

**Comment by bigbang87** [comment]
Did you tried Harpoon outside of creative mode?

**Comment by KorDum** [comment]
Yes, I used it without creative too.

**Comment by KorDum** [comment]
Mashing right mouse click on small water lake gave me hals stack of fish from one-two munute in survivor mode.

**Comment by bigbang87** [comment]
I fucked up, tested only Iron Harpoon and it's the only one that work. Fixing it right now.
