### ISSUE TITLE
[1.12.2] Topielec is buggy

### ISSUE THREAD

**Issue by KorDum** [bigbang87/deadly-monsters#13]
It attacks those in the creative.
If it caught you, you can not turn the camera and move. 100% death.

**Comment by crazyirishwrencher** [comment]
Yep. Had TLFN in my hands when he grabbed me. Did hilarious amounts of damage. Disabling monster for now.

**Comment by bigbang87** [comment]
Well, that was my original design, to make it hard as possible. You can easly kill him using Harpoon, other weapons don't work. Before changing design of this mob I would prefer to make additional text notification during fight if player use wrong weapon.

Spawn rates can be changed in config file:
```
    # Precentage Topielec spawn chance, for example 25 means 25%. [range: 0 ~ 999, default: 25]
    I:topielecSawnChance=25
```

**Comment by crazyirishwrencher** [comment]
Of course, its your mod, but as it stands I see most people disabling him. The experience doesn't feel "hard", it feels "broken".

**Comment by bigbang87** [comment]
If players feels it broken, then it's broken. I  need to figure out some solution.

**Comment by Vyraal1** [comment]
Maybe a player can break away from it, but they'll receive slowness or some form of debuffs? Only way to break away successfully is with a Harpoon? The biggest concern is just that the monster itself is localized to only a harpoon, which doesn't serve many other functions so there isn't much of an incentive to carry one around. And when you do encounter Topielec, the player is kinda SOL for not carrying this weapon with limited functionality.

**Comment by naqaden** [comment]
Topielec also ignores config speed. They cannot grab players in boats, but they think they can, so the camera jumps between the topielec and the boat repeatedly until he is dead or the player leaves the boat. I tried to alleviate this by slowing toplielecs down, but even S:topielecSpeedMultiplier=0.01 had no effect.

**Comment by Mike-U5** [comment]
While it is hilarious to see a players being dragged off into the sunset at high speed, it is a tad annoying.
Maybe let us hit them without Harpoons, but for half the damage.

**Comment by CatOfBlades** [comment]
I feel impressed by a mob that drags you down to the bottom of the ocean. But making the player feel like there's nothing they can do unless they look up the wiki and find the mobs only weakness. I have seen other mods use the riding mechanics for picking someone up. This would fix the attempt to pull players out of boats. Also the player could press shift to dismount. If instead of grabbing the player again the mob proceeded to attack any player who resisted. That way the classic mechanics could be preserved with the storyline flair. Or I am thinking maybe they drag you down to the bottom then they are vounarable to attack by standard weapons because they let you go to try to take a bite. Giving the player a chance to try to get away at high speed or fight.

**Comment by CatOfBlades** [comment]
So according to myth, the Topielec is a spirit or corpse of a drowned person specifically "Topielec" being a male victim and "Topielecia" being female. They are specifically known of in lakes or bogs and rivers. Seems a little out of character for them to spawn in packs out in the open ocean. And if they did they shouldn't hang out on the surface. I think the 1.13 implementation of the drowned mob is a far more true to myth rendition.

**Comment by getosy** [comment]
> Topielec also ignores config speed. They cannot grab players in boats, but they think they can, so the camera jumps between the topielec and the boat repeatedly until he is dead or the player leaves the boat. I tried to alleviate this by slowing toplielecs down, but even S:topielecSpeedMultiplier=0.01 had no effect.

its so powerful LOL

**Comment by getosy** [comment]
> If players feels it broken, then it's broken. I need to figure out some solution.

i hope

**Comment by ACGaming** [comment]
There's my fork [Deadly Monsters Patched](https://www.curseforge.com/minecraft/mc-mods/deadly-monsters-patched) which fixes a bunch of issues within the original mod. If there's something else to consider, please report it here: https://github.com/ACGaming/deadly-monsters/issues
