### ISSUE TITLE
1.10.2 Mobs Spawn in Light

### ISSUE THREAD

**Issue by Rahmiel** [bigbang87/deadly-monsters#3]
I've done extensive testing, even using your mod only. Deadly Monster's mobs are spawning in light levels above the limit that mobs should be spawning. My test consisted of a 7x7 chunk area in a flat world completely lit up by glowstone blocks. When I change the time to night about 4 - 6 of these mobs will spawn within that area which shouldn't be happening. This happens on both client and on the server. This is highly destructive when Mutant Steves are spawning literally in our base on the server we are running this on.

**Comment by frenzye** [comment]
yup, same issue here, specifically with freezers at the moment

**Comment by Boolyman** [comment]
I have had the same issue in my pack.  But I guess it boils down to the theory... do ALL mobs have to be vampiric in nature?  Meaning they can't be in daylight?   Reasonably, no, there should be some mobs in the modded world that are normal baddies during the day.   Well.. if thats the case, why wouldn't they be able to spawn in a light level above 7?   That makes undeniable sense.... but at the same time, this is Minecraft, and we are used to being able to protect ourselves using a piece of coal on a stick.  Meh... two sides.

**Comment by bigbang87** [comment]
That bug is fixed in the newest (1.6) version.
