### ISSUE TITLE
Conflict with Abyssal Craft

### ISSUE THREAD

**Issue by BSKCorp** [bigbang87/deadly-monsters#4]
I have noticed that when a Zombie Chicken is killed it threw an error on my console. AByssal Craft had a unknown handler and I thought it was it, but after talking with the dev it is the chicken itself throwing the error every time it is killed, something about a null check.

Here is the bug report I started with Abyssal Craft, it contains all the errors within it and the discussion me and the dev had. 

https://github.com/Shinoow/AbyssalCraft/issues/203#issuecomment-293556424

**Comment by bigbang87** [comment]
fixed in a86f80b
