### ISSUE TITLE
So many issues...

### ISSUE THREAD

**Issue by Boolyman** [bigbang87/deadly-monsters#5]
I love your mod, and I have been doing everything in my power to keep it in my modpacks, but it is getting harder and harder ever issue that comes up.

Freezer mobs break Tinker's Smeltery's by placing snow inside them.

Strangers that Piledrive players on some extra-hard blocks like the IC2 Reinforced Stone will crash the game and corrupt the world permanently.

Hardly any of your mobs respect spawn conditions like light level.

Unborn Babies blind players without even having them in line of site.  Just being in the vacinity can sometimes cause random blindness.

**Comment by mkrtes** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1570

**Comment by bigbang87** [comment]
Freezers no longer spawns snow.
All mobs respect mobGriefing gamerule, so you can disable block destruction.
Bug with spawning mobs regardless of the level of light is fixed in 1.6 wersion.
