### ISSUE TITLE
Mutant Steve block blacklist

### ISSUE THREAD

**Issue by Seth0067** [bigbang87/deadly-monsters#6]
Hi bigbang87: 

I agree with everything reported here (especially Boolyman's stuff), but would also like to add, in case you ever get around to it, having a blacklist of blocks that the mutant Steve's can't grief.  

Otherwise, the mobs in this mod are really imaginative and great, and I would encourage you to stick with active development of this content to address some of the issues raised here.  

Best of luck and hope to see you keep things up!

**Comment by bigbang87** [comment]
Right now Mutant Steven respects mobGriefing rule, that prevents him from destroying blocks
/gamerule mobGriefing false, it should
