### ISSUE TITLE
Monster Dump doesn't have a local name

### ISSUE THREAD

**Issue by Vyraal1** [bigbang87/deadly-monsters#9]
https://imgur.com/a/z6fia

It seems like the dmonsters:dump item doesn't have a local name and appears as in the link. Great mod by the way!

**Comment by bigbang87** [comment]
Thanks for info, fixed in https://github.com/bigbang87/deadly-monsters/commit/8eb186854f7a52bc204cb6e42b5ee8fd2fafdad0
